### ISSUE TITLE
Add a Why BetaML section at the top of the readme

### ISSUE THREAD

**Issue by logankilpatrick** [sylvaticus/BetaML.jl#27]
The first thing I want to know looking at this package is why would I use it? What is the big advantage over vanilla flux? It would be great to add this right at the beginning of the readme.

**Comment by sylvaticus** [comment]
Hello @logankilpatrick,  I believe the readme is quite clear in that the focus is on providing something (1) simple to use and (2) whose code is simple to understand as specialisation is preferred to generality.
This is achieved by a complementary strategy to the other ML packages, that is to embed data wrangling, individual algorithms and model evaluation in a single monolithic package.
Indeed BetaML is a collection of very different ML algorithms, not specific to Neural Networks as Flux.

Sure it will never have the completeness, generality and efficiency of the (package) composable approach, but composability of packages means to deal with generalities that introduce a learning cost for the user and development effort from the developer compared to something that works only monolithically.
As soon as most "common" stuff are implemented in BetaML, the casual ML user may find using BetaML easier than composable frameworks.

Concerning joining the Julia ML organisation, I am open to it, but what exactly does it mean? And what I have to do ?

**Comment by sylvaticus** [comment]
Hello @logankilpatrick , as said I am open to BetaML be owned by the Julia ML organisation (or AI ???). What would be the steps ?
I believe with the new `Model(autotune=true);fit!();predict()` workflow is even simpler to use!

**Comment by sylvaticus** [comment]
Closing as it seems no longer pertinent. I am still very open to share BetaML with an existing organization..
