### ISSUE TITLE
The input scitypes for trees are incorrect

### ISSUE THREAD

**Issue by ablaom** [sylvaticus/BetaML.jl#28]
From [here](https://github.com/sylvaticus/BetaML.jl/blob/8de3347bc4d8519ea7d2bcbbaf9108dcec5bdd33/src/Trees/Trees_MLJ.jl#L174):

```julia
    input_scitype    = MMI.Table(MMI.Missing, MMI.Known),           # also ok: MMI.Table(Union{MMI.Missing, MMI.Known}),
```

What is written in the comment is correct. What is actually used is not:

```julia
julia> X = (; x=[missing, 1, 2])
(x = Union{Missing, Int64}[missing, 1, 2],)

julia> scitype(X) <: Table(Missing, Known)
false

julia> scitype(X) <: Table(Union{Missing, Known})
true
```

For more on the `Table` scitype constructor, see [here](https://github.com/JuliaAI/ScientificTypesBase.jl#more-on-the-table-type).

All the tree scitypes need changing. 

Sorry that I did not pick this up in my review.

**Comment by sylvaticus** [comment]
Thanks, corrected in commit 709b857db971e69f9a1c13861f424d984a38cdcb 

By the way, supporting missing predictors makes much slower the DecisionTree algorithm. You may want to try to impute the missing values first with `MissingImputator`, based on Gaussian Mixture Models.
