### ISSUE TITLE
WARNING: could not import Perceptron ...

### ISSUE THREAD

**Issue by ablaom** [sylvaticus/BetaML.jl#38]
During precompilation  I encountered some warnings:

```
[ Info: Precompiling BetaML [024491cd-cc6b-443e-8034-08ea7eb7db2b]
WARNING: could not import Perceptron.KernelPerceptron into BetaML
WARNING: could not import Perceptron.KernelPerceptronHyperParametersSet into BetaML
WARNING: could not import Perceptron.Pegasos into BetaML
WARNING: could not import Perceptron.PegasosHyperParametersSet into BetaML
```

Maybe BetaML is importing names from Perceptron module that no longer exist?

**Comment by sylvaticus** [comment]
Was the opposite. I did add them before implementing. Sorry that it ended up in a release, it was supposed to remain in master.
These have been implemented now, so that warning should no longer appear...
