### ISSUE TITLE
Rename Nn to NN

### ISSUE THREAD

**Issue by PallHaraldsson** [sylvaticus/BetaML.jl#4]
Since you where renaming the package only two days ago, should NN also be used (more appropriate as acronym, like RBF).

I'm not sure it's advised to have both (a new module adding the old). If you change, or if not, could something like:

```
module Nn
 [init] throw("do use: using NN")
end
```

work or wise versa?

**Comment by sylvaticus** [comment]
Ah, I can't change it, as NN is already the name of the _type_ `NN` (that soon is going to become an abstract type).
So I think I will leave `Nn` as the name of the module, and `NN` as the name of the type (struct)..
