### ISSUE TITLE
Example with GaussianMixtureClusterer

### ISSUE THREAD

**Issue by juliohm** [sylvaticus/BetaML.jl#43]
Can you please provide a full example with GaussianMixtureClusterer? I tried to instantiate the type but it is giving me an error saying m is not defined.

This code used to work:

```julia
using MLJ: @load

gmm = @load GMMClusterer pkg=BetaML verbosity=0

gmm(K=4)
```

Now I understand that the new model name is GaussianMixtureClusterer, but the construction is failing.

**Comment by sylvaticus** [comment]
Thank you. I have read your message, I'll have a look later this evening or tomorrow.

**Comment by sylvaticus** [comment]
Hello, thank you for reporting. 
A bug slipped in the code evading the unit tests during the reorganisation of the package. It should now be ok in the v0.9 that I am going to release in minutes, so please update your packages to use BetaML 0.9.

Note that in the MLJ interface the name of the model is now `GaussianMixtureClusterer` and the number of classes parameter is `n_classes`.

Sorry for the confusion, but it was important to reorganise the package API. It should be much more stable now. You can read all the model names [here](https://sylvaticus.github.io/BetaML.jl/stable/index.html).

Here you have the specific model  hyperparameters:
- [here](https://sylvaticus.github.io/BetaML.jl/stable/GMM.html#BetaML.GMM.GMMClusterer) and [here](https://sylvaticus.github.io/BetaML.jl/stable/GMM.html#BetaML.GMM.GMMHyperParametersSet) for the BetaML `GMMClusterer` model
-  [here](https://sylvaticus.github.io/BetaML.jl/stable/GMM.html#BetaML.GMM.GaussianMixtureClusterer) for `GaussianMixtureClusterer` (MLJ interface)

An example of usage would then be the following:

```
import MLJBase
const Mlj = MLJBase
using BetaML

X, y                        = Mlj.@load_iris
model                       = GaussianMixtureClusterer(mixtures=FullGaussian,n_classes=3)
modelMachine                = Mlj.machine(model, X) # DimensionMismatch
(fitResults, cache, report) = Mlj.fit(model, 0, X)
yhat                        = convert(Vector{Int64},Mlj.predict_mode(model, fitResults, X))
ytrue                       = fit!(OrdinalEncoder(),y)
accuracy(ytrue,yhat,ignorelabels=true) # 0.987
```

Let me know if using BetaML v0.9 is it now working on your side !

**Comment by juliohm** [comment]
Thank you @sylvaticus , problem solved 👍🏽
