### ISSUE TITLE
Allow `verbosity`  to be any integer?

### ISSUE THREAD

**Issue by ablaom** [sylvaticus/BetaML.jl#44]
I was surprised when re-running some ecosystem-wide integration tests to get this message when training these using the MLJ interface: `MultitargetNeuralNetworkRegressor` `NeuralNetworkRegressor`:

```julia
Wrong verbosity level. Verbosity must be either 0, 10, 20, 30 or 40
```

I was probably using `verbosity =-1` to suppress warnings. 

I understand MLJ spec is mostly silent on this, but in practice the rule has been : "With the exception of warnings, training should be silent if verbosity == 0. Lower values should suppress warnings" and I would add "any integer should be allowed". 

Perhaps in the MLJ interface for the BetaML models one could map 

```julia
<= 0 -> 0
1 -> 10
2 -> 20
3 -> 30
>= 5 -> 40
```
or similar ??

**Comment by sylvaticus** [comment]
Added in [8b185a8](https://github.com/sylvaticus/BetaML.jl/commit/8b185a8cc197227ae7e277c88e501c0bc607c3d5).

**Comment by ablaom** [comment]
Thanks for the lightning response.
