### ISSUE TITLE
MLJ model docstrings

### ISSUE THREAD

**Issue by ablaom** [sylvaticus/BetaML.jl#49]
I notice that examples in docstrings use the`predict` and `fit` from `MLJModelInterface` (which are not exported by MLJ, and not intended for use by general MLJ user) rather than the machine `fit!`, `predict`, etc  methods exported by MLJ. In this respect, these model docstrings differ from all the other MLJ model docstrings, so I'd consider them "uncompliant". 

I understand this is some work to correct. Still, it would be great, for uniformity, to have these changed.

**Comment by sylvaticus** [comment]
Ok, so the idea is that pkg developers use MLJModelInterface (the "light-weight" interface) but in the doc we show users to use MLJ, correct ?

**Comment by ablaom** [comment]
Yeah, that's the idea. If you have your own native API, that can also go in the docstring, but that doesn't apply here because BetaML has separate structs for MLJ models, as I understand it. 

Here's an example: https://alan-turing-institute.github.io/MLJ.jl/dev/models/RandomForestClassifier_DecisionTree/#RandomForestClassifier_DecisionTree

**Comment by sylvaticus** [comment]
MLJ examples  in the `dev` doc section should now be compliant..
