### ISSUE TITLE
GaussianMixtureModelClusterer docstring has formatting issues

### ISSUE THREAD

**Issue by ablaom** [sylvaticus/BetaML.jl#50]
![Screen Shot 2023-02-14 at 12 39 50 PM](https://user-images.githubusercontent.com/30517088/218599136-ac9940ff-b878-4652-b04c-788668f52218.png)

**Comment by sylvaticus** [comment]
Thanks. Solved (I believe).
Going to check the rendering and then I'll close this issue.
