### ISSUE TITLE
Deprecation warning from ProgressMeter.jl

### ISSUE THREAD

**Issue by juliohm** [sylvaticus/BetaML.jl#58]
┌ BetaML [024491cd-cc6b-443e-8034-08ea7eb7db2b]
│  ┌ Warning: `Progress(n::Integer, dt::Real, desc::AbstractString = "Progress: ", barlen = nothing, color::Symbol = :green, output::IO = stderr; offset::Integer = 0)` is deprecated, use `Progress(n; dt = dt, desc = desc, barlen = barlen, color = color, output = output, offset = offset)` instead.
│  │   caller = ip:0x0
│  └ @ Core :-1

**Comment by sylvaticus** [comment]
Going to look on this, thanks!

**Comment by sylvaticus** [comment]
Hello, sorry for the delay.
In BetaML we use the macro ` @showprogress`, not the function `Progress` directly.
This seems to be unrelated to BetaML. I did open [an issue for this](https://github.com/timholy/ProgressMeter.jl/issues/279) in the ProgressMeter.jl repository. Thanks for reporting!

**Comment by sylvaticus** [comment]
I updated the `@showprogress` macro to follow the new API, the next release will not show the warning. Thank you again.
